name: using expressions and env variables

on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
    MY_NAME: "John Doe"
    BOOL: "true"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: if expression
        if: ${{ env.BOOL == 'true' }}
        run: echo "Hello $MY_NAME"
