name: strategy matrix

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: strategy matrix
        uses: ./.github/actions/strategy-matrix
        with:
          strategy: |
            {
              "os": ["ubuntu-latest", "macos-latest", "windows-latest"],
              "node": ["12", "14", "16"]
            }
      - name: print matrix
        run: echo ${{ toJSON(matrix) }}
