name: matrix and strategy

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
        - name: prints os
          run: echo ${{ matrix.os }}

 
