name: secrets and varibles

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:

  display:
    runs-on: ubuntu-latest
    steps:
      - name: Display
        run: echo ${{ secrets.SECRET_TOKEN }}

  display-variable:
    runs-on: ubuntu-latest
    steps:
      - name: Display
        run: echo ${{vars.VARIABLE}}
